name: Deploy Golang Containers to GHCR

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - d+\.d+.\d+

jobs:
  push-devcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v3

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build and push"
        uses: docker/build-push-action@v6
        with:
          file: devcontainers/golang/Dockerfile
          context: devcontainers/golang
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/ruehl/microx-golang-dev:GITHUB_REF_NAME
